name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # every Monday at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        MUNEEB706_TOKEN: ${{ secrets.MUNEEB706_TOKEN }}
      run: |-
        python build_readme.py